### ISSUE TITLE
Text Chat of Spectated Players is not Echoed to Spectator

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/FSpectate#1]
When spectating a player, their text chat (along with other nearby players) doesn't get echoed to your chat. Voice chat works fine however.

I can only verify this being an issue in DarkRP. Interestingly, this issue occurs when starting Spectate via the Scoreboard or `!spectate`, but not if started via `/spectate`, in which it'll work fine. My Server's running the latest version of DarkRP (Workshop) and also has ULX (3.70 Release - unsure if having ULX or not makes a difference - not tested). Other DarkRP servers I know of have also confirmed this to be an issue, all running Workshop DarkRP and ULX.

**Comment by FPtje** [comment]
surely then `/spectate` starts some other mod's spectate functionality

**Comment by Hazbelll** [comment]
There are no other Admin Mods, only FAdmin and ULX. If FSpectate is initiated through the Scoreboard or with `!spectate`, it'll print to text chat the Nick and SteamID of who you're spectating, but not show an FAdmin notification at the bottom of the screen. `FAdminSpectating` will return false for the Spectator.

If FSpectate is initiated with `/spectate`, it'll print to text chat the Nick and SteamID of who you're spectating, and also an FAdmin notification will pop up at the bottom of the screen saying the same (as was the old behaviour of FAdmin spectate). `FAdminSpectating` will return true for the Spectator.

**Comment by FPtje** [comment]
It seems then that !spectate triggers ULX' spectate. I thought I fixed that.

**Comment by FPtje** [comment]
Also, there is no such thing as `FAdminSpectating`, neither in FAdmin nor FSpectate.

**Comment by Hazbelll** [comment]
It exists, holding a boolean value (true) under a Player whilst they are spectating (least it did via FAdmin Spectate). It gets removed if they are not (nil).

https://github.com/FPtje/DarkRP/commit/dd79b19e55760c544d236e84f06fabca70e04f69#diff-9c785302af168fda5089f7fc50e0d612L11

It was removed entirely in that Commit, however it continues to work as it did before Spectate was ripped from FAdmin, but only when `/spectate` is used, not `!spectate` or via the Scoreboard.

When Spectating a Player:
```lua
] lua_run print(Entity(1).FAdminSpectating)
> print(Entity(1).FAdminSpectating)...
true
```

When not Spectating a Player:
```lua
] lua_run print(Entity(1).FAdminSpectating)
> print(Entity(1).FAdminSpectating)...
nil
```

**Comment by FPtje** [comment]
How can a variable that isn't set anywhere anymore still work!?

**Comment by FPtje** [comment]
Seriously, update DarkRP. Then make sure the old FAdmin spectate isn't still in the FAdmin `modules/playeractions` folder

**Comment by FPtje** [comment]
Looks like it is in the workshop version

**Comment by Hazbelll** [comment]
Well both my Server, the other servers I checked with and my own Listen Server use the Workshop version of DarkRP, so that explains everything, haha.

**Comment by FPtje** [comment]
I reckon the issue should now occur with all spectate methods, scoreboard, `/spectate` and `!spectate`. I'll look at that later.

**Comment by Hazbelll** [comment]
Thanks Falco. I have to start getting ready for my friend's funeral now, but I'll check on things too later when I can.

**Comment by FPtje** [comment]
Condolences.

**Comment by Hazbelll** [comment]
Thanks for the fix, however in DarkRP, text chat still isn't echoed to spectators. The fix hasn't been pushed into the Workshop version (only the removal of the old, FAdmin spectate files). I don't know if that was intentional for now or not, but I'd thought I'd let you know just in case.

**Comment by FPtje** [comment]
try now

**Comment by Hazbelll** [comment]
Just did. All working as expected now. Thanks again!
