### ISSUE TITLE
FSpectate still loads a invalid font

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/FSpectate#12]
surface.CreateFont("UiBold", {
        size = 16,
        weight = 800,
        antialias = true,
        shadow = false,
        font = "Default"})

**Comment by Bo98** [comment]
Didn’t realise transferring was a feature now.

**Comment by FPtje** [comment]
Yeah, it's the first time I've tried it. It's pretty cool. The issue on DarkRP now automatically redirects here.

**Comment by FPtje** [comment]
Fixed
