### ISSUE TITLE
Removal of Rank while Spectating

### ISSUE THREAD

**Issue by jonjon1234** [FPtje/FSpectate#4]
Using ULX v3.62d, ULib v2.52d, DarkRP v2.6.2, with FAdmin disabled and bundled FSpectate.

When removing a users rank, if the user is still spectating, the users chat is filled with "No Access", instead of returning the user to their prior state.

**Comment by FPtje** [comment]
Returning the user to the prior state is not done serverside. I could make a message for it, but it's probably better if the user exits themself.
