### ISSUE TITLE
Cannot switch to player inside a vehicle

### ISSUE THREAD

**Issue by MrBrax** [FPtje/FSpectate#6]
Simple as that, when freeroaming around in spectate, you can't select players inside vehicles.

**Comment by FPtje** [comment]
Yeah, I've been thinking about implementing the spectating of objects. Vehicles would fall under it.

**Comment by MrBrax** [comment]
well i was more thinking about the player inside the vehicle, if you spectate before they enter then it's gonna continue working.. but yeah that would be neat

**Comment by FPtje** [comment]
I expected you were going to say that. The point is, if I implement that idea, looking at a vehicle with a player in it and clicking the left mouse button will spectate the vehicle. It would make no sense to then create a separate feature for spectating a player within a vehicle.

**Comment by FPtje** [comment]
Besides, you can always run the command.

**Comment by MrBrax** [comment]
tru dat..

**Comment by FPtje** [comment]
would you fucking look at **that**.

Hmm yes, object spectating. You made me do it. Also, scrolling to change the third person view distance.

**Comment by MrBrax** [comment]
noice
