### ISSUE TITLE
Hook Interference

### ISSUE THREAD

**Issue by kkaptain** [FPtje/FSpectate#7]
Hello!
I have this addon on my server which allows you to use lightsabers, so when I try to go to FSpectate while in those lightsabers the following happens: https://imgur.com/OG2E0sP. The creator of the addon has a hook interference finder? (I don't even know what it's technically called.). Now I'm not completely borderline retarded with Lua and I know it's the binds having a issue when they are both bound considering that the Lighsaber allows force abilities. My best guess together with that Author of that script is that this is the culprit: https://github.com/FPtje/FSpectate/blob/4af6578c98bc3d46acd5dc53e99b1a40e039a64e/lua/fspectate/cl_init.lua#L193-L199

This is the script:
http://steamcommunity.com/sharedfiles/filedetails/?id=111412589

I don't expect you to make a workaround at all, but it's just so you know that this happens!

**Comment by FPtje** [comment]
I've taken it up with RB, but for now the solution is not to use FSpectate while holding a lightsaber.
